apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: dev
    module: namespaces
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: prod
    module: namespaces
