replicaCount: 3

image:
  repository: 949474132570.dkr.ecr.us-east-1.amazonaws.com/kubernetes-fundamentals
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

secret:
  useExternalSecrets: true
  databasePassword: ""
  apiKey: ""

storage:
  storageClassName: gp2
  size: 5Gi
