{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  hostPath:
    path: /data/{{ .Release.Name }}
{{- end }}
