apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.secret.databasePassword }}
  API_KEY: {{ .Values.secret.apiKey }}
