apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-app-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: web-app-secret
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: kubernetes-fundamentals/web-app
      property: DATABASE_PASSWORD
  - secretKey: API_KEY
    remoteRef:
      key: kubernetes-fundamentals/web-app
      property: API_KEY
