apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc
  namespace: dev
  labels:
    app: web-app
    module: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
