apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-app-pv
  labels:
    app: web-app
    module: storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/web-app
